# Generated by Django 5.1.1 on 2024-09-11 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_contact_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
    ]
